apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x7s4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-x7s4@sha256:e6929574080cc58b321f462ce4f1f5fe59399df71cfcc5665cc6d7a2fd328f2e
        name: my-nodejs
        resources: {}
status: {}
